name: Deploy to Cloud Run 2

env:
  DB_URL: ${{secrets.DB_URL}}
  SECRET_KEY: ${{secrets.SECRET_KEY}}
  DB_NAME: ${{secrets.DB_NAME}}
  DB_TEST: ${{secrets.DB_TEST}}
  EMAIL_USER: ${{secrets.EMAIL_USER}}
  EMAIL_PASS: ${{secrets.EMAIL_PASS}}
  GOOGLE_APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
    
on: [push]

env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  job_id:

    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'my-service-account@my-project.iam.gserviceaccount.com'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 363.0.0'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: Use variables
      run: |
        echo "GITHUB_SHA : $GITHUB_SHA" # Commit hash
        echo "GITHUB_REF_NAME : $GITHUB_REF_NAME" # Branca

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create file
      run: cat $GOOGLE_APPLICATION_CREDENTIALS | base64
    
    - name: Putting data
      env:
        DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $DATA > $GOOGLE_APPLICATION_CREDENTIALS

    - name: 'Deploy using gcloud CLI'
      run: |
        gcloud builds submit --tag=gcr.io/kasula/build$GITHUB_SHA
        gcloud run deploy kasula-v7 --image gcr.io/kasula/build$GITHUB_SHA --update-secrets="DB_URL=DB_URL:latest,DB_NAME=DB_NAME:latest,\
          SECRET_KEY=SECRET_KEY:latest,EMAIL_PASS=EMAIL_PASS:latest,EMAIL_USER=EMAIL_USER:latest"
