name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        - name: "Test of the variables in GitHub Actions"
          run: echo "Very secret text $VARIABLE_TEST dreta"
        - name: "Test 2 of the variables in GitHub Actions"
          run: echo "VGithub path $GITHUB_PATH dreta"
          

        # - uses: actions/checkout@v4
        # - name: Set up Python
        #   uses: actions/setup-python@v4
        #   with:
        #     python-version: '3.10'
        # - name: Install dependencies
        #   run: |
        #     python -m pip install --upgrade pip
        #     pip install pip-tools
        #     pip-compile requirements.in
        #     pip install -r requirements.txt
        
        # - name: Run tests
        #   run: |
        #     pytest